name: check 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: run lint
        run: make lint
      - name: test
        run: make jest
      - uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.KEY_CODECLIMATE}}
        with:
          coverageCommand: NODE_OPTIONS=--experimental-vm-modules npx jest --coverage
          debug: true